-- Messaging MVP:
-- - connected users can exchange direct messages freely
-- - non-connected users can send only:
--   - one optional message with a connection request
--   - one optional message with a connection request decline
-- - when a request is accepted, the request thread becomes a normal connected DM thread

create table if not exists public.message_threads (
  id bigint generated by default as identity primary key,
  thread_kind text not null check (
    thread_kind in (
      'connected_dm',
      'connection_request_dm',
      'connection_decline_dm'
    )
  ),
  connection_request_id uuid null references public.connection_requests(id) on delete set null,
  connection_user_id_a uuid null references auth.users(id) on delete cascade,
  connection_user_id_b uuid null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz null,
  last_message_preview text null
);

create unique index if not exists message_threads_request_unique_idx
  on public.message_threads (connection_request_id)
  where connection_request_id is not null;

create unique index if not exists message_threads_connected_pair_unique_idx
  on public.message_threads (connection_user_id_a, connection_user_id_b)
  where thread_kind = 'connected_dm'
    and connection_user_id_a is not null
    and connection_user_id_b is not null;

create index if not exists message_threads_last_message_idx
  on public.message_threads (last_message_at desc nulls last, created_at desc);

create table if not exists public.message_thread_participants (
  thread_id bigint not null references public.message_threads(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_message_id bigint null,
  last_read_at timestamptz null,
  is_archived boolean not null default false,
  is_muted boolean not null default false,
  primary key (thread_id, user_id)
);

create index if not exists message_thread_participants_user_idx
  on public.message_thread_participants (user_id, thread_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.message_threads(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  edited_at timestamptz null,
  deleted_at timestamptz null
);

create index if not exists messages_thread_created_idx
  on public.messages (thread_id, created_at asc, id asc);

create index if not exists messages_sender_created_idx
  on public.messages (sender_user_id, created_at desc);

alter table public.message_threads enable row level security;
alter table public.message_thread_participants enable row level security;
alter table public.messages enable row level security;

drop policy if exists "message_threads_select_participant" on public.message_threads;
create policy "message_threads_select_participant"
  on public.message_threads
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.message_thread_participants mtp
      where mtp.thread_id = message_threads.id
        and mtp.user_id = auth.uid()
    )
  );

drop policy if exists "message_thread_participants_select_own" on public.message_thread_participants;
create policy "message_thread_participants_select_own"
  on public.message_thread_participants
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "messages_select_participant" on public.messages;
create policy "messages_select_participant"
  on public.messages
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.message_thread_participants mtp
      where mtp.thread_id = messages.thread_id
        and mtp.user_id = auth.uid()
    )
  );

create or replace function public.touch_message_thread_from_message()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.message_threads
  set
    updated_at = now(),
    last_message_at = new.created_at,
    last_message_preview = left(new.body, 160)
  where id = new.thread_id;

  return new;
end;
$$;

drop trigger if exists trg_touch_message_thread_from_message on public.messages;
create trigger trg_touch_message_thread_from_message
after insert on public.messages
for each row
execute function public.touch_message_thread_from_message();

create or replace function public.are_users_connected(
  p_user_a uuid,
  p_user_b uuid
)
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.connections c
    where c.status = 'accepted'
      and (
        (c.user_id_a = p_user_a and c.user_id_b = p_user_b)
        or
        (c.user_id_a = p_user_b and c.user_id_b = p_user_a)
      )
  );
$$;

create or replace function public.ensure_message_thread_participants(
  p_thread_id bigint,
  p_user_a uuid,
  p_user_b uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.message_thread_participants (thread_id, user_id)
  values
    (p_thread_id, p_user_a),
    (p_thread_id, p_user_b)
  on conflict (thread_id, user_id) do nothing;
end;
$$;

create or replace function public.create_message_thread_for_connection_request(
  p_request_id uuid,
  p_initial_body text default null,
  p_thread_kind text default 'connection_request_dm'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid;
  v_request record;
  v_thread_id bigint;
  v_body text;
begin
  v_auth_user_id := auth.uid();

  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if p_thread_kind not in ('connection_request_dm', 'connection_decline_dm') then
    raise exception 'invalid_thread_kind';
  end if;

  select id, requester_id, target_id, status
    into v_request
  from public.connection_requests
  where id = p_request_id;

  if not found then
    raise exception 'request_not_found';
  end if;

  if v_auth_user_id not in (v_request.requester_id, v_request.target_id) then
    raise exception 'forbidden';
  end if;

  insert into public.message_threads (
    thread_kind,
    connection_request_id
  )
  values (
    p_thread_kind,
    p_request_id
  )
  on conflict (connection_request_id) do update
    set thread_kind = excluded.thread_kind,
        updated_at = now()
  returning id into v_thread_id;

  perform public.ensure_message_thread_participants(v_thread_id, v_request.requester_id, v_request.target_id);

  v_body := nullif(trim(coalesce(p_initial_body, '')), '');

  if v_body is not null then
    insert into public.messages (thread_id, sender_user_id, body)
    values (v_thread_id, v_auth_user_id, left(v_body, 4000));
  end if;

  return v_thread_id;
end;
$$;

create or replace function public.upgrade_request_message_thread_to_connected(
  p_request_id uuid
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request record;
  v_thread_id bigint;
  v_user_a uuid;
  v_user_b uuid;
begin
  select id, requester_id, target_id, status
    into v_request
  from public.connection_requests
  where id = p_request_id;

  if not found then
    raise exception 'request_not_found';
  end if;

  v_user_a := least(v_request.requester_id, v_request.target_id);
  v_user_b := greatest(v_request.requester_id, v_request.target_id);

  select id
    into v_thread_id
  from public.message_threads
  where connection_request_id = p_request_id
  limit 1;

  if v_thread_id is null then
    select mt.id
      into v_thread_id
    from public.message_threads mt
    where mt.thread_kind = 'connected_dm'
      and mt.connection_user_id_a = v_user_a
      and mt.connection_user_id_b = v_user_b
    limit 1;

    if v_thread_id is null then
      insert into public.message_threads (
        thread_kind,
        connection_request_id,
        connection_user_id_a,
        connection_user_id_b
      )
      values (
        'connected_dm',
        p_request_id,
        v_user_a,
        v_user_b
      )
      returning id into v_thread_id;
    else
      update public.message_threads
      set
        connection_request_id = coalesce(connection_request_id, p_request_id),
        updated_at = now()
      where id = v_thread_id;
    end if;
  else
    update public.message_threads
    set
      thread_kind = 'connected_dm',
      connection_user_id_a = v_user_a,
      connection_user_id_b = v_user_b,
      updated_at = now()
    where id = v_thread_id;
  end if;

  perform public.ensure_message_thread_participants(v_thread_id, v_request.requester_id, v_request.target_id);

  return v_thread_id;
end;
$$;

create or replace function public.get_or_create_connected_message_thread(
  p_other_user_id uuid
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid;
  v_thread_id bigint;
  v_user_a uuid;
  v_user_b uuid;
begin
  v_auth_user_id := auth.uid();

  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if p_other_user_id is null or p_other_user_id = v_auth_user_id then
    raise exception 'invalid_other_user';
  end if;

  if not public.are_users_connected(v_auth_user_id, p_other_user_id) then
    raise exception 'not_connected';
  end if;

  v_user_a := least(v_auth_user_id, p_other_user_id);
  v_user_b := greatest(v_auth_user_id, p_other_user_id);

  select mt.id
    into v_thread_id
  from public.message_threads mt
  where mt.thread_kind = 'connected_dm'
    and mt.connection_user_id_a = v_user_a
    and mt.connection_user_id_b = v_user_b
  limit 1;

  if v_thread_id is null then
    insert into public.message_threads (
      thread_kind,
      connection_user_id_a,
      connection_user_id_b
    )
    values (
      'connected_dm',
      v_user_a,
      v_user_b
    )
    returning id into v_thread_id;
  else
    update public.message_threads
    set updated_at = now()
    where id = v_thread_id;
  end if;

  perform public.ensure_message_thread_participants(v_thread_id, v_auth_user_id, p_other_user_id);

  return v_thread_id;
end;
$$;

create or replace function public.send_thread_message(
  p_thread_id bigint,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid;
  v_thread record;
  v_message_id bigint;
  v_other_user_id uuid;
  v_body text;
begin
  v_auth_user_id := auth.uid();

  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  select mt.*
    into v_thread
  from public.message_threads mt
  join public.message_thread_participants mtp
    on mtp.thread_id = mt.id
   and mtp.user_id = v_auth_user_id
  where mt.id = p_thread_id;

  if not found then
    raise exception 'thread_not_found';
  end if;

  v_body := nullif(trim(coalesce(p_body, '')), '');
  if v_body is null then
    raise exception 'empty_message';
  end if;

  if v_thread.thread_kind <> 'connected_dm' then
    raise exception 'thread_read_only';
  end if;

  select mtp.user_id
    into v_other_user_id
  from public.message_thread_participants mtp
  where mtp.thread_id = p_thread_id
    and mtp.user_id <> v_auth_user_id
  limit 1;

  if v_other_user_id is null then
    raise exception 'invalid_thread_participants';
  end if;

  if not public.are_users_connected(v_auth_user_id, v_other_user_id) then
    raise exception 'not_connected';
  end if;

  insert into public.messages (thread_id, sender_user_id, body)
  values (p_thread_id, v_auth_user_id, left(v_body, 4000))
  returning id into v_message_id;

  return v_message_id;
end;
$$;

create or replace function public.mark_thread_read(
  p_thread_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid;
  v_last_message_id bigint;
begin
  v_auth_user_id := auth.uid();

  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if not exists (
    select 1
    from public.message_thread_participants mtp
    where mtp.thread_id = p_thread_id
      and mtp.user_id = v_auth_user_id
  ) then
    raise exception 'thread_not_found';
  end if;

  select max(m.id)
    into v_last_message_id
  from public.messages m
  where m.thread_id = p_thread_id
    and m.deleted_at is null;

  update public.message_thread_participants
  set
    last_read_message_id = v_last_message_id,
    last_read_at = now()
  where thread_id = p_thread_id
    and user_id = v_auth_user_id;
end;
$$;

create or replace function public.get_my_unread_message_count()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(x.unread_count), 0)::int
  from (
    select count(m.id)::int as unread_count
    from public.message_thread_participants mtp
    join public.messages m
      on m.thread_id = mtp.thread_id
    where mtp.user_id = auth.uid()
      and m.deleted_at is null
      and m.sender_user_id <> auth.uid()
      and m.id > coalesce(mtp.last_read_message_id, 0)
    group by mtp.thread_id
  ) x;
$$;

create or replace function public.list_my_message_threads()
returns table (
  thread_id bigint,
  thread_kind text,
  other_user_id uuid,
  other_display_name text,
  other_avatar_url text,
  last_message_id bigint,
  last_message_body text,
  last_message_created_at timestamptz,
  last_message_sender_user_id uuid,
  unread_count integer,
  can_reply boolean
)
language sql
stable
security definer
set search_path = public
as $$
  with my_threads as (
    select
      mt.id,
      mt.thread_kind
    from public.message_threads mt
    join public.message_thread_participants mtp
      on mtp.thread_id = mt.id
    where mtp.user_id = auth.uid()
      and coalesce(mtp.is_archived, false) = false
  ),
  other_participants as (
    select
      mt.id as thread_id,
      mt.thread_kind,
      mtp.user_id as other_user_id
    from my_threads mt
    join public.message_thread_participants mtp
      on mtp.thread_id = mt.id
    where mtp.user_id <> auth.uid()
  ),
  last_messages as (
    select distinct on (m.thread_id)
      m.thread_id,
      m.id as last_message_id,
      m.body as last_message_body,
      m.created_at as last_message_created_at,
      m.sender_user_id as last_message_sender_user_id
    from public.messages m
    where m.deleted_at is null
    order by m.thread_id, m.created_at desc, m.id desc
  ),
  unread as (
    select
      mtp.thread_id,
      count(m.id)::int as unread_count
    from public.message_thread_participants mtp
    left join public.messages m
      on m.thread_id = mtp.thread_id
     and m.deleted_at is null
     and m.sender_user_id <> auth.uid()
     and m.id > coalesce(mtp.last_read_message_id, 0)
    where mtp.user_id = auth.uid()
    group by mtp.thread_id
  )
  select
    op.thread_id,
    op.thread_kind,
    op.other_user_id,
    up.display_name as other_display_name,
    up.avatar_url as other_avatar_url,
    lm.last_message_id,
    lm.last_message_body,
    lm.last_message_created_at,
    lm.last_message_sender_user_id,
    coalesce(u.unread_count, 0) as unread_count,
    (op.thread_kind = 'connected_dm') as can_reply
  from other_participants op
  left join public.user_profiles up
    on up.user_id = op.other_user_id
  left join last_messages lm
    on lm.thread_id = op.thread_id
  left join unread u
    on u.thread_id = op.thread_id
  order by coalesce(lm.last_message_created_at, now()) desc, op.thread_id desc;
$$;

create or replace function public.list_thread_messages(
  p_thread_id bigint,
  p_limit integer default 100
)
returns table (
  id bigint,
  thread_id bigint,
  sender_user_id uuid,
  body text,
  created_at timestamptz,
  sender_display_name text,
  sender_avatar_url text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    m.id,
    m.thread_id,
    m.sender_user_id,
    m.body,
    m.created_at,
    up.display_name as sender_display_name,
    up.avatar_url as sender_avatar_url
  from public.messages m
  left join public.user_profiles up
    on up.user_id = m.sender_user_id
  where m.thread_id = p_thread_id
    and m.deleted_at is null
    and exists (
      select 1
      from public.message_thread_participants mtp
      where mtp.thread_id = p_thread_id
        and mtp.user_id = auth.uid()
    )
  order by m.created_at asc, m.id asc
  limit greatest(coalesce(p_limit, 100), 1);
$$;

revoke all on function public.are_users_connected(uuid, uuid) from public;
grant execute on function public.are_users_connected(uuid, uuid) to authenticated;

revoke all on function public.ensure_message_thread_participants(bigint, uuid, uuid) from public;
revoke all on function public.create_message_thread_for_connection_request(uuid, text, text) from public;
revoke all on function public.upgrade_request_message_thread_to_connected(uuid) from public;
revoke all on function public.get_or_create_connected_message_thread(uuid) from public;
revoke all on function public.send_thread_message(bigint, text) from public;
revoke all on function public.mark_thread_read(bigint) from public;
revoke all on function public.get_my_unread_message_count() from public;
revoke all on function public.list_my_message_threads() from public;
revoke all on function public.list_thread_messages(bigint, integer) from public;

grant execute on function public.create_message_thread_for_connection_request(uuid, text, text) to authenticated;
grant execute on function public.upgrade_request_message_thread_to_connected(uuid) to authenticated;
grant execute on function public.get_or_create_connected_message_thread(uuid) to authenticated;
grant execute on function public.send_thread_message(bigint, text) to authenticated;
grant execute on function public.mark_thread_read(bigint) to authenticated;
grant execute on function public.get_my_unread_message_count() to authenticated;
grant execute on function public.list_my_message_threads() to authenticated;
grant execute on function public.list_thread_messages(bigint, integer) to authenticated;
