-- Messaging phase 2:
-- - folders: inbox / blocked
-- - starred / muted thread preferences
-- - user blocking for message threads
-- - thread reports for moderators
-- - reply-to and reactions
-- - presence + read receipt metadata

alter table public.message_thread_participants
  add column if not exists thread_folder text not null default 'inbox'
    check (thread_folder in ('inbox', 'blocked')),
  add column if not exists is_starred boolean not null default false;

create index if not exists message_thread_participants_user_folder_idx
  on public.message_thread_participants (user_id, thread_folder, is_starred, thread_id);

alter table public.messages
  add column if not exists reply_to_message_id bigint null references public.messages(id) on delete set null;

create index if not exists messages_reply_to_idx
  on public.messages (reply_to_message_id)
  where reply_to_message_id is not null;

create table if not exists public.message_reactions (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null check (char_length(trim(emoji)) between 1 and 16),
  created_at timestamptz not null default now(),
  primary key (message_id, user_id, emoji)
);

create index if not exists message_reactions_message_idx
  on public.message_reactions (message_id, created_at desc);

create table if not exists public.blocked_users (
  blocker_user_id uuid not null references auth.users(id) on delete cascade,
  blocked_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  reason text null,
  primary key (blocker_user_id, blocked_user_id),
  constraint blocked_users_not_self check (blocker_user_id <> blocked_user_id)
);

create index if not exists blocked_users_blocked_idx
  on public.blocked_users (blocked_user_id, blocker_user_id);

create table if not exists public.message_thread_reports (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.message_threads(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  reason text not null,
  details text null,
  status text not null default 'open' check (status in ('open', 'accepted', 'rejected')),
  admin_note text null,
  reviewed_at timestamptz null,
  reviewed_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists message_thread_reports_thread_status_idx
  on public.message_thread_reports (thread_id, status, created_at desc);

create index if not exists message_thread_reports_reporter_idx
  on public.message_thread_reports (reporter_user_id, created_at desc);

create table if not exists public.user_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen_at timestamptz not null default now()
);

alter table public.message_reactions enable row level security;
alter table public.blocked_users enable row level security;
alter table public.message_thread_reports enable row level security;
alter table public.user_presence enable row level security;

drop policy if exists "message_thread_participants_update_own_preferences" on public.message_thread_participants;
create policy "message_thread_participants_update_own_preferences"
  on public.message_thread_participants
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "message_reactions_select_participant" on public.message_reactions;
create policy "message_reactions_select_participant"
  on public.message_reactions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.messages m
      join public.message_thread_participants mtp
        on mtp.thread_id = m.thread_id
      where m.id = message_reactions.message_id
        and mtp.user_id = auth.uid()
    )
  );

drop policy if exists "message_reactions_insert_participant" on public.message_reactions;
create policy "message_reactions_insert_participant"
  on public.message_reactions
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.messages m
      join public.message_thread_participants mtp
        on mtp.thread_id = m.thread_id
      where m.id = message_reactions.message_id
        and mtp.user_id = auth.uid()
    )
  );

drop policy if exists "message_reactions_delete_own" on public.message_reactions;
create policy "message_reactions_delete_own"
  on public.message_reactions
  for delete
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "blocked_users_select_involving_me" on public.blocked_users;
create policy "blocked_users_select_involving_me"
  on public.blocked_users
  for select
  to authenticated
  using (auth.uid() in (blocker_user_id, blocked_user_id));

drop policy if exists "blocked_users_insert_own" on public.blocked_users;
create policy "blocked_users_insert_own"
  on public.blocked_users
  for insert
  to authenticated
  with check (blocker_user_id = auth.uid());

drop policy if exists "blocked_users_delete_own" on public.blocked_users;
create policy "blocked_users_delete_own"
  on public.blocked_users
  for delete
  to authenticated
  using (blocker_user_id = auth.uid());

drop policy if exists "message_thread_reports_select_own" on public.message_thread_reports;
create policy "message_thread_reports_select_own"
  on public.message_thread_reports
  for select
  to authenticated
  using (reporter_user_id = auth.uid());

drop policy if exists "message_thread_reports_insert_participant" on public.message_thread_reports;
create policy "message_thread_reports_insert_participant"
  on public.message_thread_reports
  for insert
  to authenticated
  with check (
    reporter_user_id = auth.uid()
    and exists (
      select 1
      from public.message_thread_participants mtp
      where mtp.thread_id = message_thread_reports.thread_id
        and mtp.user_id = auth.uid()
    )
  );

drop policy if exists "user_presence_select_authenticated" on public.user_presence;
create policy "user_presence_select_authenticated"
  on public.user_presence
  for select
  to authenticated
  using (true);

drop policy if exists "user_presence_upsert_self" on public.user_presence;
create policy "user_presence_upsert_self"
  on public.user_presence
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "user_presence_update_self" on public.user_presence;
create policy "user_presence_update_self"
  on public.user_presence
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create or replace function public.is_user_blocked_between(
  p_user_a uuid,
  p_user_b uuid
)
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.blocked_users bu
    where (bu.blocker_user_id = p_user_a and bu.blocked_user_id = p_user_b)
       or (bu.blocker_user_id = p_user_b and bu.blocked_user_id = p_user_a)
  );
$$;

create or replace function public.touch_my_presence()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid := auth.uid();
begin
  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  insert into public.user_presence (user_id, last_seen_at)
  values (v_auth_user_id, now())
  on conflict (user_id) do update
    set last_seen_at = excluded.last_seen_at;
end;
$$;

create or replace function public.set_message_thread_preferences(
  p_thread_id bigint,
  p_is_muted boolean default null,
  p_is_starred boolean default null,
  p_thread_folder text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid := auth.uid();
begin
  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if p_thread_folder is not null and p_thread_folder not in ('inbox', 'blocked') then
    raise exception 'invalid_thread_folder';
  end if;

  update public.message_thread_participants
  set
    is_muted = coalesce(p_is_muted, is_muted),
    is_starred = coalesce(p_is_starred, is_starred),
    thread_folder = coalesce(p_thread_folder, thread_folder)
  where thread_id = p_thread_id
    and user_id = v_auth_user_id;

  if not found then
    raise exception 'thread_not_found';
  end if;
end;
$$;

create or replace function public.block_message_thread_user(
  p_thread_id bigint,
  p_other_user_id uuid,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid := auth.uid();
begin
  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if p_other_user_id is null or p_other_user_id = v_auth_user_id then
    raise exception 'invalid_other_user';
  end if;

  if not exists (
    select 1
    from public.message_thread_participants mtp
    where mtp.thread_id = p_thread_id
      and mtp.user_id = v_auth_user_id
  ) then
    raise exception 'thread_not_found';
  end if;

  if not exists (
    select 1
    from public.message_thread_participants mtp
    where mtp.thread_id = p_thread_id
      and mtp.user_id = p_other_user_id
  ) then
    raise exception 'other_user_not_in_thread';
  end if;

  insert into public.blocked_users (blocker_user_id, blocked_user_id, reason)
  values (v_auth_user_id, p_other_user_id, nullif(trim(coalesce(p_reason, '')), ''))
  on conflict (blocker_user_id, blocked_user_id) do update
    set reason = excluded.reason;

  update public.message_thread_participants
  set thread_folder = 'blocked'
  where thread_id = p_thread_id
    and user_id = v_auth_user_id;
end;
$$;

create or replace function public.unblock_message_thread_user(
  p_thread_id bigint,
  p_other_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid := auth.uid();
begin
  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  delete from public.blocked_users
  where blocker_user_id = v_auth_user_id
    and blocked_user_id = p_other_user_id;

  update public.message_thread_participants
  set thread_folder = 'inbox'
  where thread_id = p_thread_id
    and user_id = v_auth_user_id;
end;
$$;

create or replace function public.report_message_thread(
  p_thread_id bigint,
  p_reason text,
  p_details text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid := auth.uid();
  v_report_id bigint;
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
  v_details text := nullif(trim(coalesce(p_details, '')), '');
begin
  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if v_reason is null then
    raise exception 'bad_request_reason';
  end if;

  if not exists (
    select 1
    from public.message_thread_participants mtp
    where mtp.thread_id = p_thread_id
      and mtp.user_id = v_auth_user_id
  ) then
    raise exception 'thread_not_found';
  end if;

  insert into public.message_thread_reports (
    thread_id,
    reporter_user_id,
    reason,
    details,
    status
  )
  values (
    p_thread_id,
    v_auth_user_id,
    left(v_reason, 200),
    case when v_details is null then null else left(v_details, 2000) end,
    'open'
  )
  returning id into v_report_id;

  return v_report_id;
end;
$$;

create or replace function public.toggle_message_reaction(
  p_message_id bigint,
  p_emoji text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid := auth.uid();
  v_emoji text := nullif(trim(coalesce(p_emoji, '')), '');
begin
  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if v_emoji is null then
    raise exception 'empty_emoji';
  end if;

  if exists (
    select 1
    from public.message_reactions mr
    where mr.message_id = p_message_id
      and mr.user_id = v_auth_user_id
      and mr.emoji = v_emoji
  ) then
    delete from public.message_reactions
    where message_id = p_message_id
      and user_id = v_auth_user_id
      and emoji = v_emoji;
  else
    insert into public.message_reactions (message_id, user_id, emoji)
    values (p_message_id, v_auth_user_id, v_emoji);
  end if;
end;
$$;

create or replace function public.send_thread_message(
  p_thread_id bigint,
  p_body text,
  p_reply_to_message_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid;
  v_thread record;
  v_message_id bigint;
  v_other_user_id uuid;
  v_body text;
begin
  v_auth_user_id := auth.uid();

  if v_auth_user_id is null then
    raise exception 'not_authenticated';
  end if;

  select mt.*
    into v_thread
  from public.message_threads mt
  join public.message_thread_participants mtp
    on mtp.thread_id = mt.id
   and mtp.user_id = v_auth_user_id
  where mt.id = p_thread_id;

  if not found then
    raise exception 'thread_not_found';
  end if;

  v_body := nullif(trim(coalesce(p_body, '')), '');
  if v_body is null then
    raise exception 'empty_message';
  end if;

  if v_thread.thread_kind <> 'connected_dm' then
    raise exception 'thread_read_only';
  end if;

  select mtp.user_id
    into v_other_user_id
  from public.message_thread_participants mtp
  where mtp.thread_id = p_thread_id
    and mtp.user_id <> v_auth_user_id
  limit 1;

  if v_other_user_id is null then
    raise exception 'invalid_thread_participants';
  end if;

  if not public.are_users_connected(v_auth_user_id, v_other_user_id) then
    raise exception 'not_connected';
  end if;

  if public.is_user_blocked_between(v_auth_user_id, v_other_user_id) then
    raise exception 'thread_blocked';
  end if;

  if p_reply_to_message_id is not null and not exists (
    select 1
    from public.messages m
    where m.id = p_reply_to_message_id
      and m.thread_id = p_thread_id
      and m.deleted_at is null
  ) then
    raise exception 'invalid_reply_target';
  end if;

  insert into public.messages (thread_id, sender_user_id, body, reply_to_message_id)
  values (p_thread_id, v_auth_user_id, left(v_body, 4000), p_reply_to_message_id)
  returning id into v_message_id;

  return v_message_id;
end;
$$;

create or replace function public.send_thread_message(
  p_thread_id bigint,
  p_body text
)
returns bigint
language sql
security definer
set search_path = public
as $$
  select public.send_thread_message(p_thread_id, p_body, null);
$$;

create or replace function public.get_my_unread_message_count()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(x.unread_count), 0)::int
  from (
    select count(m.id)::int as unread_count
    from public.message_thread_participants mtp
    join public.messages m
      on m.thread_id = mtp.thread_id
    where mtp.user_id = auth.uid()
      and coalesce(mtp.is_muted, false) = false
      and coalesce(mtp.thread_folder, 'inbox') = 'inbox'
      and m.deleted_at is null
      and m.sender_user_id <> auth.uid()
      and m.id > coalesce(mtp.last_read_message_id, 0)
    group by mtp.thread_id
  ) x;
$$;

create or replace function public.list_my_message_threads()
returns table (
  thread_id bigint,
  thread_kind text,
  other_user_id uuid,
  other_display_name text,
  other_avatar_url text,
  last_message_id bigint,
  last_message_body text,
  last_message_created_at timestamptz,
  last_message_sender_user_id uuid,
  unread_count integer,
  can_reply boolean,
  thread_folder text,
  is_starred boolean,
  is_muted boolean,
  other_last_read_message_id bigint,
  other_last_read_at timestamptz,
  other_last_seen_at timestamptz,
  other_is_online boolean,
  is_blocked_by_me boolean,
  has_blocking boolean
)
language sql
stable
security definer
set search_path = public
as $$
  with my_threads as (
    select
      mt.id,
      mt.thread_kind,
      mtp.thread_folder,
      mtp.is_starred,
      mtp.is_muted
    from public.message_threads mt
    join public.message_thread_participants mtp
      on mtp.thread_id = mt.id
    where mtp.user_id = auth.uid()
      and coalesce(mtp.is_archived, false) = false
  ),
  other_participants as (
    select
      mt.id as thread_id,
      mt.thread_kind,
      mt.thread_folder,
      mt.is_starred,
      mt.is_muted,
      mtp.user_id as other_user_id,
      mtp.last_read_message_id as other_last_read_message_id,
      mtp.last_read_at as other_last_read_at
    from my_threads mt
    join public.message_thread_participants mtp
      on mtp.thread_id = mt.id
    where mtp.user_id <> auth.uid()
  ),
  last_messages as (
    select distinct on (m.thread_id)
      m.thread_id,
      m.id as last_message_id,
      m.body as last_message_body,
      m.created_at as last_message_created_at,
      m.sender_user_id as last_message_sender_user_id
    from public.messages m
    where m.deleted_at is null
    order by m.thread_id, m.created_at desc, m.id desc
  ),
  unread as (
    select
      mtp.thread_id,
      count(m.id)::int as unread_count
    from public.message_thread_participants mtp
    left join public.messages m
      on m.thread_id = mtp.thread_id
     and m.deleted_at is null
     and m.sender_user_id <> auth.uid()
     and m.id > coalesce(mtp.last_read_message_id, 0)
    where mtp.user_id = auth.uid()
    group by mtp.thread_id
  )
  select
    op.thread_id,
    op.thread_kind,
    op.other_user_id,
    up.display_name as other_display_name,
    up.avatar_url as other_avatar_url,
    lm.last_message_id,
    lm.last_message_body,
    lm.last_message_created_at,
    lm.last_message_sender_user_id,
    coalesce(u.unread_count, 0) as unread_count,
    (
      op.thread_kind = 'connected_dm'
      and not public.is_user_blocked_between(auth.uid(), op.other_user_id)
    ) as can_reply,
    op.thread_folder,
    op.is_starred,
    op.is_muted,
    op.other_last_read_message_id,
    op.other_last_read_at,
    pr.last_seen_at as other_last_seen_at,
    (pr.last_seen_at is not null and pr.last_seen_at >= now() - interval '5 minutes') as other_is_online,
    exists (
      select 1
      from public.blocked_users bu
      where bu.blocker_user_id = auth.uid()
        and bu.blocked_user_id = op.other_user_id
    ) as is_blocked_by_me,
    public.is_user_blocked_between(auth.uid(), op.other_user_id) as has_blocking
  from other_participants op
  left join public.user_profiles up
    on up.user_id = op.other_user_id
  left join last_messages lm
    on lm.thread_id = op.thread_id
  left join unread u
    on u.thread_id = op.thread_id
  left join public.user_presence pr
    on pr.user_id = op.other_user_id
  order by
    case when coalesce(u.unread_count, 0) > 0 and coalesce(op.is_starred, false) then 0
         when coalesce(u.unread_count, 0) > 0 then 1
         when coalesce(op.is_starred, false) then 2
         else 3 end asc,
    coalesce(lm.last_message_created_at, now()) desc,
    op.thread_id desc;
$$;

create or replace function public.list_thread_messages(
  p_thread_id bigint,
  p_limit integer default 100
)
returns table (
  id bigint,
  thread_id bigint,
  sender_user_id uuid,
  body text,
  created_at timestamptz,
  sender_display_name text,
  sender_avatar_url text,
  reply_to_message_id bigint,
  reply_to_body text,
  reply_to_sender_user_id uuid,
  reaction_summary jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  with thread_messages as (
    select
      m.id,
      m.thread_id,
      m.sender_user_id,
      m.body,
      m.created_at,
      m.reply_to_message_id,
      rm.body as reply_to_body,
      rm.sender_user_id as reply_to_sender_user_id
    from public.messages m
    left join public.messages rm
      on rm.id = m.reply_to_message_id
    where m.thread_id = p_thread_id
      and m.deleted_at is null
      and exists (
        select 1
        from public.message_thread_participants mtp
        where mtp.thread_id = p_thread_id
          and mtp.user_id = auth.uid()
      )
    order by m.created_at asc, m.id asc
    limit greatest(coalesce(p_limit, 100), 1)
  ),
  reactions as (
    select
      mr.message_id,
      jsonb_agg(
        jsonb_build_object(
          'emoji', mr.emoji,
          'count', mr.cnt,
          'reactedByMe', mr.reacted_by_me
        )
        order by mr.emoji
      ) as reaction_summary
    from (
      select
        r.message_id,
        r.emoji,
        count(*)::int as cnt,
        bool_or(r.user_id = auth.uid()) as reacted_by_me
      from public.message_reactions r
      where r.message_id in (select tm.id from thread_messages tm)
      group by r.message_id, r.emoji
    ) mr
    group by mr.message_id
  )
  select
    tm.id,
    tm.thread_id,
    tm.sender_user_id,
    tm.body,
    tm.created_at,
    up.display_name as sender_display_name,
    up.avatar_url as sender_avatar_url,
    tm.reply_to_message_id,
    tm.reply_to_body,
    tm.reply_to_sender_user_id,
    coalesce(rx.reaction_summary, '[]'::jsonb) as reaction_summary
  from thread_messages tm
  left join public.user_profiles up
    on up.user_id = tm.sender_user_id
  left join reactions rx
    on rx.message_id = tm.id
  order by tm.created_at asc, tm.id asc;
$$;

revoke all on function public.is_user_blocked_between(uuid, uuid) from public;
revoke all on function public.touch_my_presence() from public;
revoke all on function public.set_message_thread_preferences(bigint, boolean, boolean, text) from public;
revoke all on function public.block_message_thread_user(bigint, uuid, text) from public;
revoke all on function public.unblock_message_thread_user(bigint, uuid) from public;
revoke all on function public.report_message_thread(bigint, text, text) from public;
revoke all on function public.toggle_message_reaction(bigint, text) from public;
revoke all on function public.send_thread_message(bigint, text, bigint) from public;

grant execute on function public.is_user_blocked_between(uuid, uuid) to authenticated;
grant execute on function public.touch_my_presence() to authenticated;
grant execute on function public.set_message_thread_preferences(bigint, boolean, boolean, text) to authenticated;
grant execute on function public.block_message_thread_user(bigint, uuid, text) to authenticated;
grant execute on function public.unblock_message_thread_user(bigint, uuid) to authenticated;
grant execute on function public.report_message_thread(bigint, text, text) to authenticated;
grant execute on function public.toggle_message_reaction(bigint, text) to authenticated;
grant execute on function public.send_thread_message(bigint, text, bigint) to authenticated;
