/*
 * File purpose
 * - Store profile card visits for the stats traffic section
 * - Allow authenticated viewers to record visits of other profiles
 * - Enforce owner-only read access through RLS
 */

begin;

create table if not exists public.profile_visits (
  id bigint generated by default as identity primary key,
  viewed_user_id uuid not null references auth.users (id) on delete cascade,
  viewer_user_id uuid not null references auth.users (id) on delete cascade,
  viewed_at timestamptz not null default now(),
  constraint profile_visits_no_self_visit_check check (viewed_user_id <> viewer_user_id)
);

create index if not exists profile_visits_viewed_at_idx
  on public.profile_visits (viewed_user_id, viewed_at desc);

create index if not exists profile_visits_viewer_at_idx
  on public.profile_visits (viewer_user_id, viewed_at desc);

alter table public.profile_visits enable row level security;

drop policy if exists "profile_visits_select_viewed_owner" on public.profile_visits;
create policy "profile_visits_select_viewed_owner"
  on public.profile_visits
  for select
  using (auth.uid() = viewed_user_id);

drop policy if exists "profile_visits_insert_as_viewer" on public.profile_visits;
create policy "profile_visits_insert_as_viewer"
  on public.profile_visits
  for insert
  with check (
    auth.uid() = viewer_user_id
    and viewed_user_id <> viewer_user_id
  );

commit;
