-- Feed post hiding + whole-post reports

create table if not exists public.hidden_posts (
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create index if not exists hidden_posts_post_idx
  on public.hidden_posts (post_id, user_id);

create table if not exists public.post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  reason text not null,
  details text null,
  status text not null default 'open' check (status in ('open', 'accepted', 'rejected')),
  admin_note text null,
  reviewed_at timestamptz null,
  reviewed_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists post_reports_post_status_idx
  on public.post_reports (post_id, status, created_at desc);

create index if not exists post_reports_reporter_idx
  on public.post_reports (reporter_user_id, created_at desc);

alter table public.hidden_posts enable row level security;
alter table public.post_reports enable row level security;

drop policy if exists "hidden_posts_select_own" on public.hidden_posts;
create policy "hidden_posts_select_own"
  on public.hidden_posts
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "hidden_posts_insert_own" on public.hidden_posts;
create policy "hidden_posts_insert_own"
  on public.hidden_posts
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "hidden_posts_delete_own" on public.hidden_posts;
create policy "hidden_posts_delete_own"
  on public.hidden_posts
  for delete
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "post_reports_select_own" on public.post_reports;
create policy "post_reports_select_own"
  on public.post_reports
  for select
  to authenticated
  using (reporter_user_id = auth.uid());

drop policy if exists "post_reports_insert_viewer" on public.post_reports;
create policy "post_reports_insert_viewer"
  on public.post_reports
  for insert
  to authenticated
  with check (
    reporter_user_id = auth.uid()
    and exists (
      select 1
      from public.posts p
      where p.id = post_reports.post_id
    )
  );
