/*
 * File purpose
 * - Add optional author stories attached to tipping posts.
 * - Store story images separately from age-guess images.
 * - Prepare story likes, story reports, and story comments.
 */

begin;

create table if not exists public.post_stories (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  body text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  hidden_by_moderation boolean not null default false,
  hidden_by_moderation_at timestamptz null,
  hidden_by_moderation_by uuid null references auth.users(id),
  hidden_by_suspension boolean not null default false,
  constraint post_stories_body_length_check check (char_length(body) <= 3000),
  constraint post_stories_one_per_post unique (post_id)
);

create table if not exists public.post_story_images (
  id bigint generated by default as identity primary key,
  story_id bigint not null references public.post_stories(id) on delete cascade,
  uploader_user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  storage_path_medium text null,
  public_url_medium text null,
  storage_path_thumb text null,
  public_url_thumb text null,
  sort_order integer not null default 0,
  alt_text text null,
  created_at timestamptz not null default now(),
  hidden_by_moderation boolean not null default false,
  hidden_by_suspension boolean not null default false,
  constraint post_story_images_alt_length_check check (alt_text is null or char_length(alt_text) <= 200)
);

create table if not exists public.post_story_likes (
  story_id bigint not null references public.post_stories(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null default 'like',
  created_at timestamptz not null default now(),
  constraint post_story_likes_pkey primary key (story_id, user_id),
  constraint post_story_likes_reaction_check check (reaction in ('like', 'clap', 'care', 'love', 'insight', 'fun'))
);

create table if not exists public.post_story_reports (
  id bigint generated by default as identity primary key,
  story_id bigint not null references public.post_stories(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text null,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz null,
  reviewed_by uuid null references auth.users(id),
  admin_note text null,
  constraint post_story_reports_reason_length_check check (char_length(reason) between 2 and 80),
  constraint post_story_reports_details_length_check check (details is null or char_length(details) <= 1000),
  constraint post_story_reports_status_check check (status in ('open', 'accepted', 'rejected'))
);

create index if not exists post_stories_post_idx on public.post_stories (post_id);
create index if not exists post_stories_author_created_idx on public.post_stories (author_user_id, created_at desc);
create index if not exists post_story_images_story_sort_idx on public.post_story_images (story_id, sort_order asc, id asc);
create index if not exists post_story_likes_story_reaction_idx on public.post_story_likes (story_id, reaction, created_at desc);
create index if not exists post_story_reports_story_status_idx on public.post_story_reports (story_id, status, created_at desc);
create index if not exists post_story_reports_reporter_idx on public.post_story_reports (reporter_user_id, created_at desc);

alter table public.comments
  add column if not exists story_id bigint null references public.post_stories(id) on delete cascade;

create index if not exists comments_story_idx
  on public.comments (story_id, created_at asc, id asc)
  where story_id is not null and target_type = 'story';

alter table public.comments
  drop constraint if exists comments_target_type_check,
  drop constraint if exists comments_target_check,
  drop constraint if exists comments_target_consistency_check;

alter table public.comments
  add constraint comments_target_type_check check (target_type in ('post', 'image', 'story')),
  add constraint comments_target_consistency_check check (
    (target_type = 'post' and post_id is not null and image_id is null and story_id is null)
    or (target_type = 'image' and post_id is not null and image_id is not null and story_id is null)
    or (target_type = 'story' and story_id is not null and image_id is null)
  );

create or replace function public.is_privileged_viewer(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_profiles up
    where up.user_id = p_user_id
      and (coalesce(up.super_user, false) = true or up.role in ('moderator', 'admin'))
  );
$$;

create or replace function public.are_accepted_contacts(p_user_a uuid, p_user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select p_user_a is not null
    and p_user_b is not null
    and (
      p_user_a = p_user_b
      or exists (
        select 1
        from public.connections c
        where c.status = 'accepted'
          and (
            (c.user_id_a = p_user_a and c.user_id_b = p_user_b)
            or (c.user_id_a = p_user_b and c.user_id_b = p_user_a)
          )
      )
    );
$$;

create or replace function public.can_view_post_for_story(p_post_id bigint, p_viewer_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  with post_ctx as (
    select
      p.id,
      p.author_user_id,
      coalesce(p.visibility, 'everyone') as post_visibility,
      p.hidden_by_suspension,
      pa.album_id,
      a.owner_user_id as album_owner_user_id,
      coalesce(a.visibility, p.visibility, 'everyone') as effective_visibility
    from public.posts p
    left join lateral (
      select album_id
      from public.post_albums
      where post_id = p.id
      order by sort_order asc, created_at asc
      limit 1
    ) pa on true
    left join public.albums a on a.id = pa.album_id
    where p.id = p_post_id
  )
  select exists (
    select 1
    from post_ctx pc
    where coalesce(pc.hidden_by_suspension, false) = false
      and p_viewer_id is not null
      and (
        public.is_privileged_viewer(p_viewer_id)
        or pc.author_user_id = p_viewer_id
        or pc.album_owner_user_id = p_viewer_id
        or pc.effective_visibility = 'everyone'
        or (
          pc.effective_visibility = 'contacts'
          and public.are_accepted_contacts(p_viewer_id, coalesce(pc.album_owner_user_id, pc.author_user_id))
        )
      )
  );
$$;

revoke all on function public.is_privileged_viewer(uuid) from public;
revoke all on function public.are_accepted_contacts(uuid, uuid) from public;
revoke all on function public.can_view_post_for_story(bigint, uuid) from public;
grant execute on function public.is_privileged_viewer(uuid) to authenticated;
grant execute on function public.are_accepted_contacts(uuid, uuid) to authenticated;
grant execute on function public.can_view_post_for_story(bigint, uuid) to authenticated;

alter table public.post_stories enable row level security;
alter table public.post_story_images enable row level security;
alter table public.post_story_likes enable row level security;
alter table public.post_story_reports enable row level security;

drop policy if exists "post_stories_select_visible" on public.post_stories;
create policy "post_stories_select_visible"
  on public.post_stories
  for select
  to authenticated
  using (
    hidden_by_moderation = false
    and hidden_by_suspension = false
    and public.can_view_post_for_story(post_id, auth.uid())
  );

drop policy if exists "post_stories_insert_own_post" on public.post_stories;
create policy "post_stories_insert_own_post"
  on public.post_stories
  for insert
  to authenticated
  with check (
    auth.uid() = author_user_id
    and exists (
      select 1 from public.posts p
      where p.id = post_stories.post_id
        and p.author_user_id = auth.uid()
        and coalesce(p.hidden_by_suspension, false) = false
    )
  );

drop policy if exists "post_stories_update_own" on public.post_stories;
create policy "post_stories_update_own"
  on public.post_stories
  for update
  to authenticated
  using (auth.uid() = author_user_id)
  with check (auth.uid() = author_user_id);

drop policy if exists "post_stories_delete_own" on public.post_stories;
create policy "post_stories_delete_own"
  on public.post_stories
  for delete
  to authenticated
  using (auth.uid() = author_user_id);

drop policy if exists "post_story_images_select_visible" on public.post_story_images;
create policy "post_story_images_select_visible"
  on public.post_story_images
  for select
  to authenticated
  using (
    hidden_by_moderation = false
    and hidden_by_suspension = false
    and exists (
      select 1 from public.post_stories ps
      where ps.id = post_story_images.story_id
        and public.can_view_post_for_story(ps.post_id, auth.uid())
    )
  );

drop policy if exists "post_story_images_insert_own_story" on public.post_story_images;
create policy "post_story_images_insert_own_story"
  on public.post_story_images
  for insert
  to authenticated
  with check (
    auth.uid() = uploader_user_id
    and exists (
      select 1 from public.post_stories ps
      where ps.id = post_story_images.story_id
        and ps.author_user_id = auth.uid()
    )
  );

drop policy if exists "post_story_images_delete_own_story" on public.post_story_images;
create policy "post_story_images_delete_own_story"
  on public.post_story_images
  for delete
  to authenticated
  using (
    exists (
      select 1 from public.post_stories ps
      where ps.id = post_story_images.story_id
        and ps.author_user_id = auth.uid()
    )
  );

drop policy if exists "post_story_likes_select_authenticated" on public.post_story_likes;
create policy "post_story_likes_select_authenticated"
  on public.post_story_likes
  for select
  to authenticated
  using (
    exists (
      select 1 from public.post_stories ps
      where ps.id = post_story_likes.story_id
        and public.can_view_post_for_story(ps.post_id, auth.uid())
    )
  );

drop policy if exists "post_story_likes_insert_own" on public.post_story_likes;
create policy "post_story_likes_insert_own"
  on public.post_story_likes
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.post_stories ps
      where ps.id = post_story_likes.story_id
        and public.can_view_post_for_story(ps.post_id, auth.uid())
    )
  );

drop policy if exists "post_story_likes_update_own" on public.post_story_likes;
create policy "post_story_likes_update_own"
  on public.post_story_likes
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "post_story_likes_delete_own" on public.post_story_likes;
create policy "post_story_likes_delete_own"
  on public.post_story_likes
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "post_story_reports_select_own" on public.post_story_reports;
create policy "post_story_reports_select_own"
  on public.post_story_reports
  for select
  to authenticated
  using (auth.uid() = reporter_user_id);

drop policy if exists "post_story_reports_insert_viewer" on public.post_story_reports;
create policy "post_story_reports_insert_viewer"
  on public.post_story_reports
  for insert
  to authenticated
  with check (
    auth.uid() = reporter_user_id
    and exists (
      select 1 from public.post_stories ps
      where ps.id = post_story_reports.story_id
        and public.can_view_post_for_story(ps.post_id, auth.uid())
    )
  );

commit;
