/*
 * File purpose
 * - Add comment reports for moderation review
 * - Allow authenticated users to report comments
 * - Keep report review available to admin tooling later
 */

begin;

create table if not exists public.comment_reports (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  reason text not null,
  details text null,
  status text not null default 'open' check (status in ('open', 'accepted', 'rejected')),
  admin_note text null,
  reviewed_at timestamptz null,
  reviewed_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists comment_reports_comment_status_idx
  on public.comment_reports (comment_id, status, created_at desc);

create index if not exists comment_reports_reporter_idx
  on public.comment_reports (reporter_user_id, created_at desc);

alter table public.comment_reports enable row level security;

drop policy if exists "comment_reports_select_own" on public.comment_reports;
create policy "comment_reports_select_own"
  on public.comment_reports
  for select
  to authenticated
  using (reporter_user_id = auth.uid());

drop policy if exists "comment_reports_insert_viewer" on public.comment_reports;
create policy "comment_reports_insert_viewer"
  on public.comment_reports
  for insert
  to authenticated
  with check (
    reporter_user_id = auth.uid()
    and exists (
      select 1
      from public.comments c
      where c.id = comment_reports.comment_id
    )
  );

commit;
