-- Notifications for network events (connection requests and responses)

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid null references auth.users(id) on delete set null,
  type text not null check (
    type in (
      'connection_request_received',
      'connection_request_accepted',
      'connection_request_declined'
    )
  ),
  entity_id uuid null,
  is_read boolean not null default false,
  read_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id, is_read, created_at desc);

alter table public.notifications enable row level security;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
  on public.notifications
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own"
  on public.notifications
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop function if exists public.create_network_notification(uuid, text, uuid);
create or replace function public.create_network_notification(
  p_target_user_id uuid,
  p_notification_type text,
  p_entity_id uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_notification_id bigint;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if p_target_user_id is null or p_target_user_id = v_actor_user_id then
    raise exception 'invalid_target_user';
  end if;

  if p_notification_type not in (
    'connection_request_received',
    'connection_request_accepted',
    'connection_request_declined'
  ) then
    raise exception 'invalid_notification_type';
  end if;

  insert into public.notifications (
    user_id,
    actor_user_id,
    type,
    entity_id
  )
  values (
    p_target_user_id,
    v_actor_user_id,
    p_notification_type,
    p_entity_id
  )
  returning id into v_notification_id;

  return v_notification_id;
end;
$$;

revoke all on function public.create_network_notification(uuid, text, uuid) from public;
grant execute on function public.create_network_notification(uuid, text, uuid) to authenticated;
